FROM peedroorgzz/nginx
USER root
# Resetear ENTRYPOINT heredado (su start.sh arranca SSH y acaba con tail -f)
ENTRYPOINT []

# Limpiar cualquier configuración por defecto que traiga la imagen base
RUN rm -f /etc/nginx/sites-enabled/default /etc/nginx/sites-available/default /etc/nginx/conf.d/default.conf

# Copiar configuración del reverse proxy
COPY nginx/gateway.conf /etc/nginx/conf.d/petstore.conf

EXPOSE 80

CMD ["/usr/sbin/nginx", "-g", "daemon off;"]
